### PR TITLE
Deprecate elk logstash cookbook

### PR DESCRIPTION
**Pull request by eherot**
Mainly involves code to do our own certificate setup but breaks backwards compatibility because it no longer installs the Cert and Key (now handled by logserver).

Required by evertrue/et_logger-cookbook#1 and by the testing components in evertrue/logserver-cookbook#1

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
:+1: from me, :shipit:

**Comment by jeffbyrnes** [comment]
This still looks good.

**Comment by EdHurtig** [comment]
looks good

**Comment by EdHurtig** [comment]
Amazing beautiful, best code ever!

:stuck_out_tongue:

**Pull request merged**
